# Generated by Django 4.1.3 on 2023-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0002_page_is_favorite_page_is_public"),
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="editable_pages",
            field=models.ManyToManyField(
                blank=True, related_name="edit_users", to="notion_models.page"
            ),
        ),
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
