# Generated by Django 4.1.3 on 2023-04-13 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=36)),
                ("icon", models.CharField(default="E", max_length=1)),
                ("index", models.IntegerField(default=0)),
                ("is_root", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.IntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("T", "Text"),
                            ("P", "Page"),
                            ("1", "Heading 1"),
                            ("2", "Heading 2"),
                            ("3", "Heading 3"),
                            ("4", "Heading 4"),
                            ("5", "Heading 5"),
                            ("6", "Heading 6"),
                            ("B", "Bulleted List"),
                            ("N", "Numbered List"),
                            ("D", "To-do List"),
                            ("Q", "Quote"),
                            ("C", "Code"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                ("indentation", models.IntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="notion_models.page",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notion_models.text",
                    ),
                ),
            ],
            options={"ordering": ["index"],},
        ),
    ]
