# Generated by Django 4.1.3 on 2022-11-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("isBold", models.BooleanField(default=False)),
                ("isItalic", models.BooleanField(default=False)),
            ],
        ),
    ]
