# Generated by Django 4.1.3 on 2023-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
