# Generated by Django 4.1.3 on 2022-11-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0002_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="text", old_name="isBold", new_name="is_bold",
        ),
        migrations.RenameField(
            model_name="text", old_name="isItalic", new_name="is_italic",
        ),
    ]
