# Generated by Django 4.1.3 on 2022-11-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0004_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
