# Generated by Django 4.1.3 on 2022-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0005_delete_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="text", name="is_bold",),
        migrations.RemoveField(model_name="text", name="is_italic",),
        migrations.AddField(
            model_name="page",
            name="icon",
            field=models.CharField(default="E", max_length=1),
        ),
        migrations.AlterField(
            model_name="text", name="text", field=models.TextField(default=""),
        ),
    ]
