# Generated by Django 4.1.3 on 2023-04-07 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "notion_models",
            "0006_remove_text_is_bold_remove_text_is_italic_page_icon_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
