# Generated by Django 4.1.3 on 2023-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0008_alter_page_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="page", name="index", field=models.IntegerField(default=0),
        ),
    ]
