# Generated by Django 4.1.3 on 2023-04-07 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0009_page_index"),
    ]

    operations = [
        migrations.RemoveField(model_name="page", name="text",),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.IntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("T", "Text"),
                            ("P", "Page"),
                            ("1", "Heading 1"),
                            ("2", "Heading 2"),
                            ("3", "Heading 3"),
                            ("4", "Heading 4"),
                            ("5", "Heading 5"),
                            ("6", "Heading 6"),
                            ("B", "Bulleted List"),
                            ("N", "Numbered List"),
                            ("D", "To-do List"),
                            ("Q", "Quote"),
                            ("C", "Code"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                ("indentation", models.IntegerField(default=0)),
                (
                    "text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notion_models.text",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.ManyToManyField(
                blank=True, related_name="page", to="notion_models.pagecontent"
            ),
        ),
    ]
