# Generated by Django 4.1.3 on 2023-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0010_remove_page_text_pagecontent_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_root_page",
            field=models.BooleanField(default=True),
        ),
    ]
