# Generated by Django 4.1.3 on 2023-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion_models", "0011_page_is_root_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page", old_name="is_root_page", new_name="is_root",
        ),
    ]
